display_name: EchoLLM
package_name: echollm

maintainer:
  name: Alabi Ayobami
  email: arocket04@gmail.com

priority: optional

section: x11

installed_size: 15700

dependencies:


essential: false

icon: ./assets/icon.png

postuninstall_scripts:
  - echo "Sorry to see you go."

keywords:
  - AI
  - LLM inference

generic_name: EchoLLM

categories:
  - Development
  - Utility
  - AI

startup_notify: true