name: echollm
version: '1.0.0'
summary: A privacy-focused AI chat application
description: |
  EchoLLM is a desktop client for interacting with various AI models
  with local API key management and chat history storage.

base: core22
confinement: devmode
grade: devel

apps:
  echollm:
 
 
    desktop: snap/gui/echo_llm.desktop
    plugs:
      - network
      - network-bind
      - home
      - x11
      - wayland
      - opengl
      - pulseaudio
      - gsettings
      - removable-media

parts:
 

  echollm:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart
    build-snaps:
      - flutter/latest/stable
    build-packages:
      - clang
      - cmake
      - ninja-build
      - libgtk-3-dev
      - liblzma-dev
    stage-packages:
      - libgtk-3-0
      - libcolord2   
 