name: echollm
version: '1.0.0'
summary: A privacy-focused AI chat application
description: |
  EchoLLM is a desktop client for interacting with various AI models
  with local API key management and chat history storage.

base: core22
confinement: strict
grade: stable

apps:
  echollm:
    command: bin/desktop-launch $SNAP/echollm # Corrected command path
    extensions: [gnome] # The gnome extension provides desktop-launch
    desktop: usr/share/applications/echollm.desktop
    plugs:
      - network
      - network-bind
      - home
      - x11
      - wayland
      - opengl
      - pulseaudio
      - gsettings
      - removable-media

parts:
  echollm:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart
    # The flutter build-snap needs to be in the part that uses it
    build-snaps:
      - flutter/latest/stable
    build-packages:
      - clang
      - cmake
      - ninja-build
      - libgtk-3-dev
      - liblzma-dev
    stage-packages:
      - libgtk-3-0
      # You may not need all of these as the gnome extension provides many
      # - libgl1
      # - libx11-6
      # - libxcb1
      # - libxkbcommon0
      # - libatomic1