name: echollm
version: '1.0.0'
summary: A privacy-focused AI chat application
description: |
  EchoLLM is a desktop client for interacting with various AI models
  with local API key management and chat history storage.

base: core24
confinement: devmode
grade: devel

architectures:
  - build-on: amd64

apps:
  echollm:
    command: echo_llm
    desktop: snap/gui/echo_llm.desktop
    plugs:
      - network
      - network-bind
      - home
      - x11
      - wayland
      - opengl
      - pulseaudio
      - gsettings
      - removable-media
    
    environment:
      XDG_DATA_DIRS: "$SNAP/usr/share:$XDG_DATA_DIRS"
      GTK_PATH: "$SNAP/usr/lib/x86_64-linux-gnu/gtk-3.0"

parts:
  echollm:
    source: .
    source-type: git
    plugin: flutter
    flutter-target: lib/main.dart
    build-snaps:
      - flutter/latest/stable
    build-packages:
      - clang
      - cmake
      - ninja-build
      - libgtk-3-dev
      - liblzma-dev
    stage-packages:
      - libgtk-3-0
      - libcolord2
    
      - gnome-themes-extra
      - adwaita-icon-theme
      - hicolor-icon-theme
      - gtk2-engines-murrine
      - librsvg2-common
      - libgdk-pixbuf2.0-0
      - libgdk-pixbuf2.0-bin
      - shared-mime-info
