name: echollm
version: '1.0.0'
summary: A privacy-focused AI chat application
description: |
  EchoLLM is a desktop client for interacting with various AI models.

base: core22
confinement: devmode
grade: devel

architectures:
  - build-on: amd64

apps:
  echollm:
    command: echo_llm
    extensions: [gnome] # This is the "magic" line
    desktop: snap/gui/echo_llm.desktop
    plugs:
      - network
      - network-bind
      - home
      - opengl
      - pulseaudio
      - gsettings
      - removable-media
    # DELETE the "environment:" block entirely. 
    # The gnome extension sets those variables correctly for you.

parts:
  echollm:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart
    build-snaps:
      - flutter/latest/stable
    build-packages:
      - clang
      - cmake
      - ninja-build
      - libgtk-3-dev
      - liblzma-dev
    stage-packages:
      - libgtk-3-0
    # I removed the long list of icon-themes and pixbuf packages. 
    # The gnome extension includes them automatically in a more compatible way.
