name: echollm
version: '1.0.0'
summary: A privacy-focused AI chat application
description: |
  EchoLLM is a desktop client for interacting with various AI models
  with local API key management and chat history storage.

 
license: Apache-2.0   

base: core22
confinement: strict  
grade: stable        

architectures:
  - build-on: amd64

apps:
  echollm:
    command: echo_llm
    extensions: [gnome]
    desktop: snap/gui/echo_llm.desktop
    plugs:
      - network
      - network-bind
      - home
      - opengl
      - pulseaudio
      - gsettings
      - removable-media

parts:
  echollm:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart
    build-snaps:
      - flutter/latest/stable
    build-packages:
      - clang
      - cmake
      - ninja-build
      - libgtk-3-dev
      - liblzma-dev
    stage-packages:
      - libgtk-3-0
